# fly.toml file generated for replica-p2p-quic-reverse-proxy on 2022-02-28T16:35:18+01:00

app = "replica-p2p-quic-reverse-proxy"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "quicreverseproxy-deploy.dockerfile"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "udp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["proxy_proto", "tls", "http"]
    port = 80
