addr: 127.0.0.1:18345
autoLaunch: true
autoReport: true
language: ""
localHTTPToken: f7d2fa987e88b95d3c622b38b890b627
proxyAll: true
socksAddr: 127.0.0.1:18346
systemProxy: true
uiAddr: localhost:16823
userID: 1
userToken: ""
