// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package issue

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type Request struct {
	Type                 string                `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CountryCode          string                `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	AppVersion           string                `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	SubscriptionLevel    string                `protobuf:"bytes,4,opt,name=subscription_level,json=subscriptionLevel,proto3" json:"subscription_level,omitempty"`
	Platform             string                `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Description          string                `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	UserEmail            string                `protobuf:"bytes,7,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Attachments          []*Request_Attachment `protobuf:"bytes,8,rep,name=attachments,proto3" json:"attachments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Request) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *Request) GetSubscriptionLevel() string {
	if m != nil {
		return m.SubscriptionLevel
	}
	return ""
}

func (m *Request) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Request) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Request) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *Request) GetAttachments() []*Request_Attachment {
	if m != nil {
		return m.Attachments
	}
	return nil
}

type Request_Attachment struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Attachment) Reset()         { *m = Request_Attachment{} }
func (m *Request_Attachment) String() string { return proto.CompactTextString(m) }
func (*Request_Attachment) ProtoMessage()    {}
func (*Request_Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1, 0}
}

func (m *Request_Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Attachment.Unmarshal(m, b)
}
func (m *Request_Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Attachment.Marshal(b, m, deterministic)
}
func (m *Request_Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Attachment.Merge(m, src)
}
func (m *Request_Attachment) XXX_Size() int {
	return xxx_messageInfo_Request_Attachment.Size(m)
}
func (m *Request_Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Attachment proto.InternalMessageInfo

func (m *Request_Attachment) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request_Attachment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request_Attachment) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "issue.Response")
	proto.RegisterType((*Request)(nil), "issue.Request")
	proto.RegisterType((*Request_Attachment)(nil), "issue.Request.Attachment")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbf, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xd5, 0xdf, 0xed, 0xb9, 0x0b, 0x37, 0x99, 0x4a, 0x88, 0xd0, 0xa9, 0x0b, 0x19, 0x60,
	0x64, 0x42, 0x88, 0x0d, 0x31, 0x64, 0x60, 0x8d, 0xdc, 0xe4, 0x10, 0x91, 0x12, 0xdb, 0xf8, 0x2e,
	0x95, 0xfa, 0xaf, 0x33, 0xa1, 0xb8, 0x6d, 0xc8, 0xc0, 0x76, 0xef, 0xbd, 0x6f, 0xb0, 0x3e, 0x83,
	0x92, 0xa3, 0x27, 0x4e, 0x7d, 0x70, 0xe2, 0x70, 0x56, 0x31, 0xb7, 0xb4, 0x05, 0x58, 0x66, 0xc4,
	0xde, 0x59, 0xa6, 0xed, 0xcf, 0x18, 0x16, 0x19, 0x7d, 0xb7, 0xc4, 0x82, 0x08, 0xd3, 0x8e, 0xd6,
	0xa3, 0x64, 0xb4, 0x5b, 0x65, 0xf1, 0xc6, 0x3b, 0x58, 0x17, 0xae, 0xb5, 0x12, 0x8e, 0x79, 0xe1,
	0x4a, 0xd2, 0xe3, 0xb8, 0xa9, 0x73, 0xf7, 0xe2, 0x4a, 0xc2, 0x5b, 0x50, 0xc6, 0xfb, 0xfc, 0x40,
	0x81, 0x2b, 0x67, 0xf5, 0x24, 0x12, 0x60, 0xbc, 0xff, 0x38, 0x35, 0x78, 0x0f, 0xc8, 0xed, 0x9e,
	0x8b, 0x50, 0x79, 0xa9, 0x9c, 0xcd, 0x6b, 0x3a, 0x50, 0xad, 0xa7, 0x91, 0xbb, 0x1a, 0x2e, 0x6f,
	0xdd, 0x80, 0x1b, 0x58, 0xfa, 0xda, 0xc8, 0xa7, 0x0b, 0x8d, 0x9e, 0x45, 0xa8, 0xcf, 0x98, 0x80,
	0x2a, 0xa9, 0xe7, 0xf5, 0xfc, 0xf4, 0x9a, 0x41, 0x85, 0x37, 0x00, 0x2d, 0x53, 0xc8, 0xa9, 0x31,
	0x55, 0xad, 0x17, 0x11, 0x58, 0x75, 0xcd, 0x6b, 0x57, 0xe0, 0x13, 0x28, 0x23, 0x62, 0x8a, 0xaf,
	0x86, 0xac, 0xb0, 0x5e, 0x26, 0x93, 0x9d, 0x7a, 0xb8, 0x4e, 0xa3, 0x98, 0xf4, 0x2c, 0x22, 0x7d,
	0xee, 0x89, 0x6c, 0x48, 0x6f, 0xde, 0x01, 0xfe, 0xa6, 0x7f, 0x75, 0x21, 0x4c, 0xad, 0x69, 0x2e,
	0x9a, 0xe2, 0x8d, 0x1a, 0x16, 0x85, 0xb3, 0x42, 0x56, 0xa2, 0x9b, 0x75, 0x76, 0x89, 0xfb, 0x79,
	0xfc, 0x96, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x70, 0x00, 0xa2, 0xa5, 0x01, 0x00,
	0x00,
}
