// Code generated by MockGen. DO NOT EDIT.
// Source: ./genconfig.go
//
// Generated by this command:
//
//	mockgen -destination ./mock_genconfig.go -source ./genconfig.go -package main verifier, tlsDialer
//

// Package main is a generated GoMock package.
package main

import (
	x509 "crypto/x509"
	net "net"
	reflect "reflect"
	time "time"

	fronted "github.com/getlantern/fronted"
	tlsdialer "github.com/getlantern/tlsdialer/v3"
	tls "github.com/refraction-networking/utls"
	gomock "go.uber.org/mock/gomock"
)

// Mockverifier is a mock of verifier interface.
type Mockverifier struct {
	ctrl     *gomock.Controller
	recorder *MockverifierMockRecorder
}

// MockverifierMockRecorder is the mock recorder for Mockverifier.
type MockverifierMockRecorder struct {
	mock *Mockverifier
}

// NewMockverifier creates a new mock instance.
func NewMockverifier(ctrl *gomock.Controller) *Mockverifier {
	mock := &Mockverifier{ctrl: ctrl}
	mock.recorder = &MockverifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockverifier) EXPECT() *MockverifierMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *Mockverifier) ISGOMOCK() struct{} {
	return struct{}{}
}

// Vet mocks base method.
func (m_2 *Mockverifier) Vet(m *fronted.Masquerade, pool *x509.CertPool, testURL string) bool {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Vet", m, pool, testURL)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Vet indicates an expected call of Vet.
func (mr *MockverifierMockRecorder) Vet(m, pool, testURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vet", reflect.TypeOf((*Mockverifier)(nil).Vet), m, pool, testURL)
}

// MocktlsDialer is a mock of tlsDialer interface.
type MocktlsDialer struct {
	ctrl     *gomock.Controller
	recorder *MocktlsDialerMockRecorder
}

// MocktlsDialerMockRecorder is the mock recorder for MocktlsDialer.
type MocktlsDialerMockRecorder struct {
	mock *MocktlsDialer
}

// NewMocktlsDialer creates a new mock instance.
func NewMocktlsDialer(ctrl *gomock.Controller) *MocktlsDialer {
	mock := &MocktlsDialer{ctrl: ctrl}
	mock.recorder = &MocktlsDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktlsDialer) EXPECT() *MocktlsDialerMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MocktlsDialer) ISGOMOCK() struct{} {
	return struct{}{}
}

// DialForTimings mocks base method.
func (m *MocktlsDialer) DialForTimings(dial func(string, string, time.Duration) (net.Conn, error), timeout time.Duration, network, addr string, sendServerName bool, config *tls.Config) (*tlsdialer.ConnWithTimings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialForTimings", dial, timeout, network, addr, sendServerName, config)
	ret0, _ := ret[0].(*tlsdialer.ConnWithTimings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialForTimings indicates an expected call of DialForTimings.
func (mr *MocktlsDialerMockRecorder) DialForTimings(dial, timeout, network, addr, sendServerName, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialForTimings", reflect.TypeOf((*MocktlsDialer)(nil).DialForTimings), dial, timeout, network, addr, sendServerName, config)
}
