name: Build and Push flashlight tester image
on:
  push:
    branches: [main]
jobs:
  docker_push:
    name: docker push
    runs-on:
      group: large-runners
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      - uses: google-github-actions/auth@v2
        id: google_auth
        with:
          token_format: access_token
          workload_identity_provider: projects/472305719257/locations/global/workloadIdentityPools/github-actions/providers/ghactions-provider
          service_account: ghactions@lantern-cloud.iam.gserviceaccount.com

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.google_auth.outputs.access_token }}

      - name: docker push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "github_token=${{ secrets.CI_PRIVATE_REPOS_GH_TOKEN }}"
          file: ./tester/Dockerfile
          tags: |
            us-docker.pkg.dev/lantern-cloud/containers/flashlight-tester:latest
            us-docker.pkg.dev/lantern-cloud/containers/flashlight-tester:${{ github.sha }}
