name: Update Global Config

on:
  push:
    branches:
      - main
      - 220907_soltzen_debug_flashlight
    paths:
      - 'embeddedconfig/global.yaml.tmpl'
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Granting private modules access
      run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
    - uses: actions/checkout@v3
      with:
        ref: 220907_soltzen_debug_flashlight
    - name: Go generate
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: |
        cd ./embeddedconfig
        go generate
    - name: Go test
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      run: |
        cd ./config
        go test -v -failfast -count=1 -race
    - name: Git push
      uses: actions/checkout@v3
      with:
        ref: 220907_soltzen_debug_flashlight
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add embeddedconfig/global.yaml
        git commit -m "pushing auto-generated embedded global config"
        echo "pushing to main"
        git push origin main
